# Generated by Django 3.2.5 on 2021-07-28 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('age', models.IntegerField(blank=True)),
                ('dob', models.DateField(verbose_name='Date Of Birth')),
                ('school', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('R', 'Rather Not Say')], default=('R', 'Rather Not Say'), max_length=1)),
                ('department_discipline', models.CharField(max_length=250, verbose_name='Department/Discipline')),
                ('any_position_held', models.CharField(blank=True, max_length=250, verbose_name='Any Position Held')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Detail',
                'verbose_name_plural': 'User Details',
            },
        ),
    ]
