# Generated by Django 3.2.5 on 2021-08-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='school',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='school_or_inst',
            field=models.CharField(default='unilag', max_length=250, verbose_name='School or Institution'),
            preserve_default=False,
        ),
    ]
