# Generated by Django 3.2.5 on 2021-08-22 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0002_auto_20210809_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='owner',
            new_name='user',
        ),
    ]
