# Generated by Django 3.2.5 on 2021-08-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0004_auto_20210822_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
