# Generated by Django 3.2.5 on 2021-07-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_question_survey'),
        ('surveys', '0002_alter_survey_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='questions',
            field=models.ManyToManyField(to='questions.Question'),
        ),
    ]
