# Generated by Django 3.2.5 on 2021-07-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emptytextfield',
            name='text_field',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
