# Generated by Django 3.2.5 on 2021-08-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response_fields', '0002_alter_emptytextfield_text_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicefield',
            name='level',
        ),
        migrations.RemoveField(
            model_name='choicefield',
            name='question_field',
        ),
        migrations.RemoveField(
            model_name='choicefield',
            name='title',
        ),
        migrations.DeleteModel(
            name='EmptyTextField',
        ),
    ]
